/**
 * =============================================================================
 * FILE: app/api/tables/[tableName]/modify/route.ts
 * =============================================================================
 *
 * PRESENTATION GUIDE — what to tell your teacher
 * ─────────────────────────────────────────────────────────────────────────────
 * This file is the backend API handler for ALL Data Manipulation Language (DML)
 * operations in the Stellar Archive DBMS project.
 *
 * It exposes three HTTP endpoints on the route:
 *   POST   /api/tables/:tableName/modify  → INSERT
 *   PUT    /api/tables/:tableName/modify  → UPDATE
 *   DELETE /api/tables/:tableName/modify  → DELETE
 *
 * Every query uses the `pg` (node-postgres) library to run RAW, PARAMETERIZED
 * SQL directly against PostgreSQL — no ORM, no query builder.
 *
 * TOPICS COVERED IN THIS FILE
 * ────────────────────────────
 *  • DML — INSERT INTO … VALUES (…) RETURNING *
 *  • DML — UPDATE … SET … WHERE … RETURNING *
 *  • DML — DELETE FROM … WHERE … RETURNING *
 *  • Parameterized queries ($1, $2 …) — SQL injection prevention
 *  • Primary Keys — identifying rows uniquely for UPDATE / DELETE
 *  • NOT NULL constraint enforcement — server-side validation before INSERT
 *  • Column-level allowlisting — preventing writes to auto-generated columns
 *    (e.g. SERIAL primary keys, created_at with DEFAULT NOW())
 *  • RETURNING clause — fetch the affected row back in the same round-trip
 *  • Connection pooling — `pool` from src/lib/db.ts (pg.Pool)
 * =============================================================================
 */

import pool from "@/lib/db";

// ── Security: Table Allowlist ────────────────────────────────────────────────
//
// PRESENTATION POINT — SQL Injection Prevention (Table Names)
// Only tables in this list can be modified. Table names cannot be parameterized
// with $1 in PostgreSQL (only VALUES can be), so we validate them here manually.
// If a caller sends tableName = "users; DROP TABLE users", it is rejected.
//
const ALLOWED_TABLES = ["celestial_bodies", "observations"] as const;
type AllowedTable = (typeof ALLOWED_TABLES)[number];

// ── Schema Metadata ──────────────────────────────────────────────────────────
//
// PRESENTATION POINT — Primary Keys
// Each table has a PRIMARY KEY column (SERIAL, auto-incremented by PostgreSQL).
// We need it to identify *which* row to UPDATE or DELETE.
//   celestial_bodies → body_id  (INTEGER PRIMARY KEY)
//   observations     → obs_id   (INTEGER PRIMARY KEY)
//
const PK: Record<AllowedTable, string> = {
  celestial_bodies: "body_id",
  observations:     "obs_id",
};

// PRESENTATION POINT — Column Allowlist for UPDATE (SET clause)
// We never allow updating the primary key itself, or system columns like
// created_at. Only the columns listed here can appear in the SET clause.
// This prevents accidental corruption of primary keys or audit timestamps.
//
const UPDATABLE_COLS: Record<AllowedTable, string[]> = {
  celestial_bodies: ["name", "spectral_type", "mass", "distance_ly", "constellation", "discovered_at"],
  observations:     ["body_id", "observed_at", "notes", "observer", "instrument"],
};

// PRESENTATION POINT — Column Allowlist for INSERT
// Only these columns are accepted in an INSERT. The primary key (body_id /
// obs_id) is omitted — it is auto-generated by the SERIAL type in PostgreSQL
// (equivalent to AUTO_INCREMENT in MySQL). created_at also has DEFAULT NOW().
//
const INSERTABLE_COLS: Record<AllowedTable, string[]> = {
  celestial_bodies: ["name", "spectral_type", "mass", "distance_ly", "constellation", "discovered_at"],
  observations:     ["body_id", "observed_at", "notes", "observer", "instrument"],
};

function isAllowed(t: string): t is AllowedTable {
  return (ALLOWED_TABLES as readonly string[]).includes(t);
}

async function resolveParams(params: Promise<{ tableName: string }>) {
  return params;
}

// =============================================================================
// DML OPERATION 1 — INSERT
// =============================================================================
//
// PRESENTATION POINT — INSERT INTO … VALUES (…) RETURNING *
//
// Raw SQL executed (example for celestial_bodies):
//
//   INSERT INTO "celestial_bodies" ("name", "spectral_type", "mass")
//   VALUES ($1, $2, $3)
//   RETURNING *;
//
// Key concepts:
//  • $1, $2, $3 … are PARAMETERIZED PLACEHOLDERS. The actual values are
//    passed separately in an array — PostgreSQL substitutes them safely,
//    preventing SQL injection even if the value contains quotes or semicolons.
//  • RETURNING * — PostgreSQL extension that returns the inserted row
//    (including the auto-generated body_id / obs_id) without a second SELECT.
//  • The column list is built dynamically from only the fields the client sent
//    that are also in INSERTABLE_COLS — blank / null fields are skipped.
//
export async function POST(
  req: Request,
  { params }: { params: Promise<{ tableName: string }> }
) {
  const { tableName } = await resolveParams(params);
  if (!isAllowed(tableName))
    return Response.json({ error: `Inserts into "${tableName}" are not allowed.` }, { status: 400 });

  let body: Record<string, unknown>;
  try { body = await req.json(); } catch {
    return Response.json({ error: "Invalid JSON body." }, { status: 400 });
  }

  // Filter to only allowed, non-empty columns sent by the client
  const allowed = INSERTABLE_COLS[tableName];
  const cols = Object.keys(body).filter(
    (k) => allowed.includes(k) && body[k] !== "" && body[k] !== null && body[k] !== undefined
  );

  if (cols.length === 0)
    return Response.json({ error: "No valid fields provided." }, { status: 400 });

  // PRESENTATION POINT — NOT NULL Constraint (application-level enforcement)
  // Before hitting the DB, we check the NOT NULL columns ourselves so we can
  // return a clear error message. PostgreSQL would also reject it, but with a
  // less readable error string.
  //   celestial_bodies.name       → NOT NULL
  //   observations.body_id        → NOT NULL, REFERENCES celestial_bodies(body_id)
  if (tableName === "celestial_bodies" && !body["name"])
    return Response.json({ error: "Field 'name' is required." }, { status: 400 });
  if (tableName === "observations" && !body["body_id"])
    return Response.json({ error: "Field 'body_id' is required." }, { status: 400 });

  // Build the parameterized query dynamically
  const placeholders = cols.map((_, i) => `$${i + 1}`).join(", ");
  const values       = cols.map((c) => body[c]);
  // Example output: INSERT INTO "celestial_bodies" ("name","mass") VALUES ($1,$2) RETURNING *
  const sql = `INSERT INTO "${tableName}" (${cols.map((c) => `"${c}"`).join(", ")}) VALUES (${placeholders}) RETURNING *`;

  try {
    const start  = Date.now();
    const result = await pool.query(sql, values);  // ← raw pg query
    return Response.json(
      { success: true, row: result.rows[0], rowsAffected: result.rowCount, queryTime: Date.now() - start },
      { status: 201 }  // 201 Created
    );
  } catch (err: unknown) {
    return Response.json({ error: err instanceof Error ? err.message : "Unknown error" }, { status: 500 });
  }
}

// =============================================================================
// DML OPERATION 2 — UPDATE
// =============================================================================
//
// PRESENTATION POINT — UPDATE … SET … WHERE … RETURNING *
//
// Raw SQL executed (example: update body_id=3 with new name and mass):
//
//   UPDATE "celestial_bodies"
//   SET "name" = $1, "mass" = $2
//   WHERE "body_id" = $3
//   RETURNING *;
//
// Key concepts:
//  • WHERE clause with the PRIMARY KEY — ensures we update exactly one row.
//    Without WHERE, UPDATE would modify every row in the table.
//  • SET clause is built dynamically. Only fields the client sent are included.
//    Empty-string values are treated as NULL (clearing the field).
//  • $1 … $N are parameterized — values array passed separately to pool.query().
//  • RETURNING * — get the modified row back without an extra SELECT.
//  • rowCount === 0 check — if no row matched the PK, return 404.
//
export async function PUT(
  req: Request,
  { params }: { params: Promise<{ tableName: string }> }
) {
  const { tableName } = await resolveParams(params);
  if (!isAllowed(tableName))
    return Response.json({ error: `Updates on "${tableName}" are not allowed.` }, { status: 400 });

  let body: Record<string, unknown>;
  try { body = await req.json(); } catch {
    return Response.json({ error: "Invalid JSON body." }, { status: 400 });
  }

  // PRESENTATION POINT — Primary Key required for UPDATE
  // We must know WHICH row to update. The client sends the PK value alongside
  // the fields to change. We separate the PK from the SET columns below.
  const pkCol = PK[tableName];
  const pkVal = body[pkCol];
  if (pkVal === undefined || pkVal === null || pkVal === "")
    return Response.json({ error: `Primary key "${pkCol}" is required.` }, { status: 400 });

  const allowed = UPDATABLE_COLS[tableName];
  const setCols = Object.keys(body).filter(
    (k) => k !== pkCol && allowed.includes(k) && body[k] !== undefined
  );

  if (setCols.length === 0)
    return Response.json({ error: "No updatable fields provided." }, { status: 400 });

  // Build SET clause: "name" = $1, "mass" = $2
  // PK goes in as the LAST parameter: WHERE "body_id" = $N
  const setClause = setCols.map((c, i) => `"${c}" = $${i + 1}`).join(", ");
  const values    = [...setCols.map((c) => body[c] === "" ? null : body[c]), pkVal];
  const sql       = `UPDATE "${tableName}" SET ${setClause} WHERE "${pkCol}" = $${setCols.length + 1} RETURNING *`;

  try {
    const start  = Date.now();
    const result = await pool.query(sql, values);  // ← raw pg query
    if (result.rowCount === 0)
      return Response.json({ error: `No record found with ${pkCol} = ${pkVal}.` }, { status: 404 });
    return Response.json(
      { success: true, row: result.rows[0], rowsAffected: result.rowCount, queryTime: Date.now() - start }
    );
  } catch (err: unknown) {
    return Response.json({ error: err instanceof Error ? err.message : "Unknown error" }, { status: 500 });
  }
}

// =============================================================================
// DML OPERATION 3 — DELETE
// =============================================================================
//
// PRESENTATION POINT — DELETE FROM … WHERE … RETURNING *
//
// Raw SQL executed (example: delete the row where body_id = 5):
//
//   DELETE FROM "celestial_bodies"
//   WHERE "body_id" = $1
//   RETURNING *;
//
// Key concepts:
//  • WHERE with the PRIMARY KEY is mandatory — same reason as UPDATE.
//    A DELETE without WHERE would wipe the entire table (full table delete).
//  • RETURNING * — returns the deleted row so the UI can confirm what was removed.
//  • ON DELETE CASCADE — because the observations table has:
//      body_id INTEGER REFERENCES celestial_bodies(body_id) ON DELETE CASCADE
//    deleting a celestial body automatically deletes all its linked observations.
//    This is a FOREIGN KEY constraint enforced by PostgreSQL at the DB level.
//  • rowCount === 0 — no row matched → return 404 rather than silently succeeding.
//
export async function DELETE(
  req: Request,
  { params }: { params: Promise<{ tableName: string }> }
) {
  const { tableName } = await resolveParams(params);
  if (!isAllowed(tableName))
    return Response.json({ error: `Deletes on "${tableName}" are not allowed.` }, { status: 400 });

  let body: Record<string, unknown>;
  try { body = await req.json(); } catch {
    return Response.json({ error: "Invalid JSON body." }, { status: 400 });
  }

  // PRESENTATION POINT — Primary Key required for DELETE (same reason as UPDATE)
  const pkCol = PK[tableName];
  const pkVal = body[pkCol];
  if (pkVal === undefined || pkVal === null || pkVal === "")
    return Response.json({ error: `Primary key "${pkCol}" is required.` }, { status: 400 });

  // Simple single-parameter DELETE — only $1 needed (the PK value)
  const sql = `DELETE FROM "${tableName}" WHERE "${pkCol}" = $1 RETURNING *`;

  try {
    const start  = Date.now();
    const result = await pool.query(sql, [pkVal]);  // ← raw pg query
    if (result.rowCount === 0)
      return Response.json({ error: `No record found with ${pkCol} = ${pkVal}.` }, { status: 404 });
    return Response.json(
      { success: true, row: result.rows[0], rowsAffected: result.rowCount, queryTime: Date.now() - start }
    );
  } catch (err: unknown) {
    return Response.json({ error: err instanceof Error ? err.message : "Unknown error" }, { status: 500 });
  }
}
